### ISSUE TITLE
Governance > W3C - Suggestions

### ISSUE THREAD

**Issue by koalie** [bocoup/web-platform-contribution-guide#133]
Hi!

Here are a couple corrections:
s/20 or so employees/60 or so employees/
s/Technical Plenary Advisory Committee/Technical Plenary and Advisory Committee meetings week/

It's not obvious why the guide puts the emphasis on "CSS WG" and "ARIA" as sub-topics.

Perhaps you'd be amenable to augment the paragraph above with something like:
`<a href="https://www.w3.org/Consortium/activities">34
 working groups and 10 interest groups</a> enable W3C to
 pursue its mission through the creation of Web standards,
 guidelines, and supporting materials, with over 
<a href="https://w3c.github.io/spec-dashboard/report.html">250 
active specifications</a> tracked. `

**Comment by zcorpan** [comment]
Thank you for the feedback @koalie ! Yes, we should fix this.

The CSS WG and ARIA are discussed as examples, and what we have prior experience with. I think it would make sense to remove those subsections and have a more overreaching description of W3C work, and your input here is very relevant and valuable. We will follow up on this shortly.
