### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by zcorpan** [bocoup/web-platform-contribution-guide#146]
https://github.com/bocoup/web-platform-contribution-guide/pull/145 is failing in CircleCI with this error:

```
make dirhtml
Running Sphinx v2.3.1

Warning, treated as error:
node class 'meta' is already registered, its visitors will be overridden
make: *** [Makefile:20: dirhtml] Error 2

Exited with code exit status 2
```

I could reproduce this same error locally on `master` also. Not sure what's up.

cc @mariestaver

**Comment by mariestaver** [comment]
@zcorpan It looks like this could be due to a known issue with Sphinx -- is this project using docutils-0.18?  If so, we may need to downgrade to 0.17 to fix it (from https://github.com/sphinx-doc/sphinx/issues/9841).
